<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>cn.city-parking</groupId>
    <artifactId>city-parking-config-spring-boot-starter</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>city-parking-config-spring-boot-starter</name>
    <description>config</description>
    <packaging>jar</packaging>
    <parent>
        <groupId>cn.city-parking</groupId>
        <artifactId>city-parking-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath/>
    </parent>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.ofpay</groupId>
            <artifactId>logback-mdc-ttl</artifactId>
        </dependency>
        <!--日志收集-->
        <dependency>
            <groupId>de.siegmar</groupId>
            <artifactId>logback-gelf</artifactId>
        </dependency>
    </dependencies>
</project>
